

all:
	g++ -std=c++11 -O3 -march=native -I. ./main.cpp ./small_utils.cpp ./bubble_sort.cpp ./merge_sort.cpp ./shell_sort.cpp ./insertion_sort.cpp ./heap_sort.cpp ./binary_search.cpp ./reverse_list.cpp ./radix_sort_msd.cpp ./string_search.cpp -o sorter
